inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - config/**/*
    - vendor/**/*
    - db/**/*
    - bin/**/*

RSpec/InstanceVariable:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Rails/FilePath:
  Enabled: false


Metrics/AbcSize:
  Enabled: true
  Exclude:
    - 'app/extensions/derivatives.rb'

Metrics/BlockLength:
  Enabled: true
  ExcludedMethods: ['feature', 'before', 'describe', 'context', 'scenario', 'configure', 'config', 'setup', 'class_eval']
  Exclude:
    - config/**/*
    - lib/tasks/**/*
    - 'app/controllers/catalog_controller.rb'

Metrics/ClassLength:
  Exclude:
    - 'app/uploaders/csv_manifest_validator.rb'
    - 'app/controllers/catalog_controller.rb'

Metrics/MethodLength:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

Rails/Delegate:
  Exclude:
    - 'app/models/csv_import.rb'

RSpec/DescribeClass:
  Exclude:
    - 'spec/system/**/*'

RSpec/ExampleLength:
  Enabled: false
  Exclude:
    - 'spec/features**/*'
    - 'spec/system/**/*'
    - 'spec/uploaders/csv_manifest_validator_spec.rb'
    - 'spec/importers/modular_importer_spec.rb'

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Style/EmptyMethod:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false
